# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "07fec3725cc11e2320aa663f86b403cf"
application_url = "https://conversation-designation-vacuum-bridal.trycloudflare.com"
embedded = false
name = "non-embeded-app"
handle = "non-embeded-app"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_orders"

[auth]
redirect_urls = [
  "https://conversation-designation-vacuum-bridal.trycloudflare.com/auth/callback",
  "https://conversation-designation-vacuum-bridal.trycloudflare.com/auth/shopify/callback",
  "https://conversation-designation-vacuum-bridal.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "store4app.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[app_proxy]
url = "https://conversation-designation-vacuum-bridal.trycloudflare.com/api/proxy/liquid"
subpath = "non-embeded-app"
prefix = "apps"
